using System;

namespace LeadisTeam.LeadisJourney.Core.Entities
{
    // UserExperience = Code generated by the user
    public class UserExperience : IEntity
    {
        public int Id { get; set; }
        public User Creator { get; set; }
        public DateTime CreationDate { get; set; }
        public string Code { get; set; }

        //private String etat;  etat ?
        //private ExperienceResult result;
        //ExperienceResult ? UserExperienceTreatement ?
    }
}